name: deploy to lambda
on: [push]
jobs:

  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1

      - name: Configure AWS credentials # install and configure aws cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: zip file
        run: |
          sudo apt install zip
          zip send-email.zip send-email.py


      - name: deploy zip to aws lambda
        run: |
          aws lambda update-function-code \
            --function-name  send-email \
            --zip-file send-email.zip